### PR TITLE
Winners interviews

### PR DESCRIPTION
**Pull request by michaeld123**
Thanks for making this repo - its a great idea.
How about putting links to the winners interviews as well as the forum entries?
They are a bit easier to read as they are presented as an article rather than a bunch of posts.

This fork has a script that makes a list of all URLs of the winners interviews, they just need to be matched to the competitions and put into the competitions.json file. I'm happy to give it a shot, just wanted to clarify if you actually wanted them or just the forums?

Getting the paths to the forum discussion of the final submissions for each competition most likely can't be automated and would involve someone looking at each project.

Cheers,
Michael

### CODE REVIEW

**Comment by EliotAndres** [comment]
Great idea! Thank you for this list. Do you think we should put them in a separate column ?

**Comment by michaeld123** [comment]
Sorry for the late reply, I think a separate column would be best as once you have a few forums and winners interviews each row would get quite big.

Also, I've found these websites, the first one is very similar to yours. 
They look like good resources to scrape links.
http://dsg.rushter.com/competitions/
http://www.chioka.in/kaggle-competition-solutions/
https://www.kaggle.com/wiki/PastSolutions

Is it possible to filter the columns? i.e. find all Classification problems.

**Comment by EliotAndres** [comment]
I added a new column for the winners interviews. It would be nice if you could move your script in the ./scripts folder.

Thank you for the websites. I saw some of them but they are outdated, that's why I created this repo 😄 

Regarding filtering: the search is on all fields so you can search "classification" and it'll show you all rows containing this word. Do you think a per-column filter is necessary ?

**Comment by michaeld123** [comment]
Thanks - you're right filtering is fine as is.
I do like this repo better than those other sites, I'm keen to get it more filled in and up to date.

When I get some time, I'll edit my script to match urls with the competitions and get it to output to competitions.json, then I'll move to the scripts dir.
After that I'll see what I can do about scraping the sites to fill in more of the fields.

**Comment by EliotAndres** [comment]
As some people added interviews, I'm closing this.

**Pull request closed without merging**
